### ISSUE TITLE
Live preview is broken

### ISSUE THREAD

**Issue by josircg** [fseesink/django-adminlte3-tutorial#2]
Hi folks, the live preview is broken. 

https://github.com/fseesink/django-adminlte3-tutorial/blob/413af512cfcc2856d8d38668939a2f0135e814f3/README.md?plain=1#L204

Do you have another link showing how it works?

**Comment by fseesink** [comment]
Hey @josircg,

Sorry for slow response.  Thanks for letting me know.

I just checked and you are correct.  I went and checked the site.  Seems they moved the live preview page here:  https://adminlte.io/themes/v3/

So I updated the link to match.
